#!/data/data/com.termux/files/usr/bin/bash
#
# This is a termux-url-opener script to do diffrent tasks on my Android phone 
#
#
#
# How to use this script
#############################
#  Install wget and ffmpeg
# ➜ pkg install wget ffmpeg python
# https://wiki.termux.com/wiki/Shells
#
## Install yt-dlp and scdl with pip
# ➜ pip install yt-dlp
# ➜ pip install scdl mutagen
##
# Create the bin directory
# ➜ ~ cd bin
#
# Download the script
# ➜ ~ wget https://gist.githubusercontent.com/LordH3lmchen/dc35e8df3dc41d126683f18fe44ebe17/raw/fec1b164219c4c1714d13cb65acb81c57ec25572/termux-url-opener
# 
# Make it executable
# ➜ chmod +x termux-url-opener

# run the following command to enable the termux storage features
# ➜ termux-setup-storage
# https://wiki.termux.com/wiki/Termux-setup-storage
#
#
# Feel free to fork it and clone it (alternative way to get the script to the phone)
# 
# ➜ ~ mkdir bin
#
# ➜ ~ git clone git@gist.github.com:dc35e8df3dc41d126683f18fe44ebe17.git termux-url-opener
# (replace with your fork if you want)
#
# ➜ ~ ln -s $HOME/termux-url-opener/termux-url-opener bin/termux-url-opener
# now you can modify it on your phone and use git to update the script
#
# use "git pull" to get the latest version.
#
#

url=$1
echo "What should I do with $url ?"
echo "y) download youtube video to movies-folder"
echo "u) download youtube video and convert it to mp3 (music-folder)"
echo "s) download with scdl (soundcloud)"
echo "w) wget file to download-folder" 
echo "x) nothing"

read CHOICE
case $CHOICE in
    y)
        yt-dlp -o "/storage/emulated/0/Movies/%(title)s.%(ext)s" $url
	;;
    u)
	echo "Artist"
	read artist
	echo "Title"
	read title
	echo "Album"
	read album
	yt-dlp --extract-audio --audio-format mp3 --output "/storage/emulated/0/Music/$artist-$title.%(ext)s" $url
	mid3v2 -a $artist -t $title -A $album /storage/emulated/0/Music/$artist-$title.mp3
	;;
    s)
	scdl -l $url --path /storage/emulated/0/Music
        echo "s need some work"
	;;
    w)
        cd ~/storage/downloads
	wget $url
	;;
    x)
        echo "bye"
	;; 
esac
